#!/bin/bash

function mk_setenv {
	build=$1
	if [ "$build" == "" ]; then
    	build="debug"
	fi
	export build
	export rootdir=`pwd`
	export srcdir=$rootdir/src
	export libdir=$rootdir/lib
	export bindir=$rootdir/bin
}

function mk_setdefaults {
	#linkopts="+L +S -X"
	linkopts="-P"
	export linkopts
	case "$1" in
	    "release" ) buildopts="-D +O -P";;
	    "debug" ) buildopts="+D -O -R -P";;
	esac
	export buildopts
	makelibopts="-P"
	export makelibopts
}

function mk_printenv {
	echo "-------------------------------------------"
	echo "Building  : $1"
	echo "Config    : $build"
	echo "CC Opts   : $buildopts"
	echo "LINK Opts : $linkopts"
	echo "ROOT DIR  : $rootdir"
	echo "SRC DIR   : $srcdir"
	echo "BIN DIR   : $bindir"
	echo "LIB DIR   : $libdir"
	echo "-------------------------------------------"
}

function mk_createfolders {
	thisdir=$1
	if [ "$thisdir" == "" ]; then
    	thisdir="."
	fi
	#if [ ! -d $thisdir/temp ]; then
	#	mkdir $thisdir/temp
	#fi
	rm -rf $thisdir/temp/*
	if [ ! -d $thisdir/lib ]; then
		mkdir $thisdir/lib
	fi
	rm -rf $thisdir/lib/*
	if [ ! -d $thisdir/bin ]; then
		mkdir $thisdir/bin
	fi
	rm -rf $thisdir/bin/*
}

function mk_cleanfolders {
	thisdir=$1
	if [ "$thisdir" == "" ]; then
    	thisdir="."
	fi
	#rm -rf $thisdir/temp
}

function mk_movebinifexist {
	filepath=$1
	todir=$2
	existcheck=`ls $filepath 2> /dev/null` 
	if [ "$existcheck" != "" ]; then
    	mv $filepath $todir
	fi
	
}

function mk_movebin {
	fromdir=$1
	todir=$2
	if [ "$fromdir" == "" ]; then
    	fromdir="."
	fi
	if [ "$todir" == "" ]; then
    	todir="./bin"
	fi
	mk_movebinifexist "$fromdir/*.a" $todir
	mk_movebinifexist "$fromdir/*.sym" $todir
	mk_movebinifexist "$fromdir/*.root" $todir
	mk_movebinifexist "$fromdir/*.A" $todir
	mk_movebinifexist "$fromdir/*.SYM" $todir
	mk_movebinifexist "$fromdir/*.ROOT" $todir
}

