#!/bin/bash

source ../mktools

mk_setenv $1
mk_setdefaults $build

mk_printenv "tslib"

mk_createfolders $rootdir

mk_cleanfolders $rootdir

cd $srcdir
iix compile \
	$buildopts \
	ini.c \
	utils.c \
	tsarray.c \
	tslist.c \
	tsstring.c \
	tsmem.c

mk_movebin $srcdir $bindir

cd $bindir
iix makelib \
	$makelibopts \
	$libdir/tslib \
	+tsarray.a \
	+tslist.a \
	+ini.a \
	+utils.a \
	+tsstring.a \
	+tsmem.a
	
	
cp $srcdir/*.h $libdir

cd $rootdir






