#!/bin/bash

source ../mktools

mk_setenv $1
mk_setdefaults $build

mk_printenv "tslib"

mk_createfolders $rootdir

mk_cleanfolders $rootdir

cd $srcdir
$runiix compile \
	$buildopts \
	ini.c \
	utils.c \
	tsarray.c \
	tslist.c \
	tsstring.c \
    getopt.c \
    tslog.c \
	tsmem.c \
	nucrc16.c

if [[ "$?" != "0" ]] 
then
echo "exiting"
	exit 1
fi

mk_movebin $srcdir $bindir

cd $bindir
$runiix makelib \
	$makelibopts \
	$libdir/tslib \
	+tsarray.a \
	+tslist.a \
	+ini.a \
    +getopt.a \
    +tslog.a \
	+utils.a \
	+tsstring.a \
	+tsmem.a \
	+nucrc16.a
	
if [[ "$?" != "0" ]] 
then
echo "exiting"
	exit 1
fi
	
cp $srcdir/*.h $libdir

cd $rootdir






