#!/bin/bash

source ../mktools

mk_setenv $1
mk_setdefaults $build

mk_printenv "tslib_test"

mk_createfolders $rootdir

rm -rf $libdir

mk_cleanfolders $rootdir

cd $srcdir
$runiix  compile $buildopts \
	tslib_test_main.c

if [[ "$?" != "0" ]] 
then
echo "exiting"
	exit 1
fi

mk_movebin $srcdir $bindir

cd $bindir
$runiix  link $linkopts tslib_test_main.a ../../tslib/lib/tslib keep=tslib_test

if [[ "$?" != "0" ]] 
then
echo "exiting"
	exit 1
fi

cd $rootdir














