#!/bin/bash

source ../mktools

mk_setenv $1
mk_setdefaults $build

mk_printenv "tsspilib"

mk_createfolders $rootdir

cd $srcdir
iix compile $buildopts tsspilib.c
iix compile $buildopts tsspilib_asm_spireadb.asm
iix compile $buildopts tsspilib_asm_spisendb.asm

mk_movebin $srcdir $bindir

cd $bindir
iix makelib \
	$makelibopts \
	$libdir/tsspilib \
	+tsspilib.a \
	+tsspilib_asm_spisendb.ROOT \
	+tsspilib_asm_spireadb.ROOT 

cp $srcdir/tsspilib.h $libdir
cd $rootdir

mk_cleanfolders $rootdir

