#!/bin/bash

source ../mktools

mk_setenv $1
mk_setdefaults $build

mk_printenv "tssocketlib"

mk_createfolders $rootdir

cd $srcdir
iix compile \
	$buildopts \
	tssocketlib.c \
	tssocketlib_w5500.c

mk_movebin $srcdir $bindir

cd $bindir
iix makelib \
	$makelibopts \
	$libdir/tssocketlib \
	+tssocketlib.a \
	+tssocketlib_w5500.a

cp $srcdir/tssocketlib.h $libdir
cp $srcdir/tssocketlib_w5500.h $libdir
cd $rootdir

mk_cleanfolders $rootdir

