#!/bin/bash

source ../mktools

mk_setenv $1
mk_setdefaults $build

mk_printenv "spidl"

mk_createfolders $rootdir

rm -rf $libdir

mk_cleanfolders $rootdir

cd $srcdir
iix compile $buildopts \
	spidl_main.c

mk_movebin $srcdir $bindir

cd $bindir
iix link $linkopts \
	spidl_main.a \
	../../tslib/lib/tslib \
	../../tssocketlib/lib/tssocketlib \
	../../tsspilib/lib/tsspilib \
	keep=spidl

cd $rootdir














